name: Windows-CI

on:
  push:
    branches: 
      - isomorphic
    tags:
      - '*'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - name: Branch name
        id: branch_name
        run: |
          echo ::set-output name=SOURCE_NAME::${GITHUB_REF#refs/*/}
          echo ::set-output name=SOURCE_BRANCH::${GITHUB_REF#refs/heads/}
          echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}
        shell: bash

      - uses: actions/setup-java@v1
        with:
          java-version: "8.x"
      - uses: subosito/flutter-action@v1
        with:
          channel: "dev"

      - name: Change flutter channel to master, enable windows support
        run: |
          flutter channel master
          flutter upgrade
          flutter config --enable-windows-desktop
          flutter pub get

      - name: Build windows
        run: |
          flutter build windows

      - name: Prepare release files
        run: |
          7z a -tzip flutter_ui_challenges-windows-x64-${{ steps.branch_name.outputs.SOURCE_NAME }}.zip -r .\build\windows\x64\Release\Runner\*

      - uses: xresloader/upload-to-github-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: flutter_ui_challenges-windows-x64-${{ steps.branch_name.outputs.SOURCE_NAME }}.zip
          tags: true
          draft: false